### ISSUE TITLE
Memperbarui ke Laravel 6.x

### ISSUE THREAD

**Issue by Djenova** [NgeSEC/relawan#100]
Mengingat projek ini menggunakan laravel 5.5 versi LTS yang lama, saya mengusulkan untuk memperbarui versi ke laravel 6.0 LTS, bilamana usulan ini diterima, minggu ini saya dan @meiichin akan mengerjakannya, atau mungkin ada usulan untuk porting ke framework lain dimana teman teman lebih familiar.

Ref : https://laravel.com/docs/master/releases

Terima kasih. :wink: :bowing_man:

**Comment by DyanGalih** [comment]
@Djenova Upgrade ke versi 6 aja

**Comment by meiichin** [comment]
Halo teman-teman semua, ketika saya melakukan update ke laravel versi 6.0, saya mendapatkan issue dari package yang terintegrasi didalamnya. yaitu package webappid/content. dikarenakan package tersebut saya update ke versi terbarunya yang sudah support dengan laravel versi 6.0

![image](https://user-images.githubusercontent.com/44971341/67300210-d2ba7a00-f517-11e9-84e3-020a58af0379.png)

Setelah saya telusuri errornya:

![image](https://user-images.githubusercontent.com/44971341/67300342-01385500-f518-11e9-891d-d94495cd70b1.png)
Source pada: app/repositories/PlaceRepository.php
yang dimana pada function tersebut memanggil function dari vendor package dari webappid/content

![image](https://user-images.githubusercontent.com/44971341/67300944-f7632180-f518-11e9-923d-16514b20ee54.png)

function pertama memanggil function pada package dengan 1 param yang membuat function yang dipanggil dari vendor memiliki default value null, lalu function dengan default value null tersebut memangil function lain yang telah diberi tipe data integer, karena system membaca null bukanlah integer maka terjadilah error, dan jika tipe data tersebut dihapus website dapat berjalan lagi.

![image](https://user-images.githubusercontent.com/44971341/67301512-b15a8d80-f519-11e9-9e93-e3d46e204334.png)

kenapa packagenya saya update, dikarenakan package yang lama tidak support illuminate 6.*, dan maksimal versi laravel yang didapat adalah versi 5.8

mungkin bisa dibantu mas @DyanGalih sekalu author dari package tersebut hehe
Terima kasih ^^

**Comment by Djenova** [comment]
laravel 7 release notes https://laravel.com/docs/7.x/releases
