### ISSUE TITLE
Kekurangan Dokumentasi (Kebutuhan PHP Unit)

### ISSUE THREAD

**Issue by Djenova** [NgeSEC/relawan#22]
1. Penjelasan bagaimana menyiapkan php unit
2. Penjelasan bagaimana menjalankan php unit

**Comment by endoch** [comment]
mas @Djenova 

apakah dokumen berikut sudah menjawab:
https://github.com/NgeSEC/relawan/wiki/Cara-Menjalankan-Unit-Test

**Comment by Djenova** [comment]
Baik mas @endoch terimakasih atas wikinya. Saya rasa itu sudah cukup menjawab
