### ISSUE TITLE
Kekurangan Dokumentasi (Forking)

### ISSUE THREAD

**Issue by Djenova** [NgeSEC/relawan#23]
1. Persiapan Forking
2. Melaksanakan Forking
3. Menjalankan Aplikasi

Nuwun

**Comment by endoch** [comment]
mas @Djenova 
https://github.com/NgeSEC/relawan/wiki/Cara-Fork-Repository-Relawan

apakah dokumen wiki tersebut sudah sesuai dengan poin nomer 1 dan 2 yang mas utarakan?

**Comment by Djenova** [comment]
Siap mas @endoch, terimakasih untuk **Gambaran Umum Proses Fork** dan  **Cara Fork Repository Relawan** cukup jelas,  untuk poin Sinkronisasi Fork mungkin mas @resxar bisa membantu, 
kemudian di bagian depan readme sepertinya harus di tambah point
1. Jika ingin berkontribusi harus melalui forking 
2. Jika ingin mencoba bisa langsung clone repo NgeSEC/relawan 

WTK @resxar
