### ISSUE TITLE
Kekurangan Dokumentasi (Sinkron Repo)

### ISSUE THREAD

**Issue by resxar** [NgeSEC/relawan#32]
Gimana cara buat update repo dari forking kita supaya updatenya sama kayak repo di Ngesec/relawan?

WTK: @banumelody

**Comment by endoch** [comment]
mas @resxar,
apakah [wiki](https://github.com/NgeSEC/relawan/wiki/Alur-Kerja-Repository-Relawan#langkah-teknis-berkontribusi) berikut sudah menjawab?

**Comment by resxar** [comment]
belum om, barusan saya coba pake ini bisa supaya repo di saya jadi last updated

1. git stash
2. git pull upstream master
3. git push
4. php artisan migrate
5. composer update
6. npm run dev
7. php artisan serve

WTK: @endoch

**Comment by DyanGalih** [comment]
@resxar Kenapa harus git stash ya?

**Comment by yohang88** [comment]
Selama kita coding di branch sendiri (terpisah dari `master`), misal branch `feature-abc`, biasanya tidak perlu / jarang kejadian perlu di-*stash*, karena branch master di local kita tetap sama dengan master dari origin/upstream. Ya ini bagian dari **git-flow** yang dimensyen di group 😀 

Jadi kalau saya biasanya selalu bikin branch baru untuk fitur/percobaan, tidak di `master`. Overall deskripsi di [Wiki](https://github.com/NgeSEC/relawan/wiki/Alur-Kerja-Repository-Relawan#langkah-teknis-berkontribusi) menurut saya sudah cukup jelas. Tidak berbeda dengan cara kerja saya pribadi selama ini.

Btw saya mau menyoroti langkah nomor 5 : `composer update`, menurut saya jika tidak ada perubahan di `composer.json`, tidak ada penambahan packages baru, tidak perlu menjalankan `composer update`, melainkan cukup `composer install`. Selain itu prosesnya juga lebih cepat dibandingkan `composer update`.

`composer update` biasanya dijalankan jika menambahkan/ada perubahan di file `composer.json`, atau perlu update packages ke latest version. Dan ini biasanya jarang-jarang. Kalaupun perlu ada update, hanya perlu dilakukan 1 orang, misal oleh **lead developer**. Karena setiap update version, pasti perlu dicek compability-nya/banyak hal yang perlu dicek.

Referensi:
1. https://adamcod.es/2013/03/07/composer-install-vs-composer-update.html
2. https://www.engineyard.com/blog/composer-its-all-about-the-lock-file

cmiiw 😀

**Comment by endoch** [comment]
> belum om, barusan saya coba pake ini bisa supaya repo di saya jadi last updated
> 
> git stash
> git pull upstream master
> git push
> php artisan migrate
> composer update
> npm run dev
> php artisan serve

sesuai arahan dari bapak pm @banumelody, langkah nomer 2 dari yang mas @resxar tuliskan, yaitu _git pull upstream master_ seharusnya adalah _git pull —rebase upstream master_ untuk menghindari commit yang bertumpuk (commit yang baru justru ada di bawah commit yang lama).

dengan asumsi:
- git remote -v menunjukkan origin ke rexsar/relawan dan upstream ke ngesec/relawan 
- git status menunjukkan file yang belum ke staged adalah public/css/app.css dan public/js/app.js maka selain ```git stash```, mas @resxar bisa melakukan ```git reset --hard```.

tujuan yang dicapai adalah supaya origin/master sama (sinkron) dengan upstream, maka:
 - command git pull --rebase upstream master memang harus dilakukan pada branch master 
 - git push 
- setelah  itu bisa buka di akun github, keterangan yang tadinya ```behind ngesec/relawan``` akan menjadi ```this branch is even with ngesec/relawan```

sedangkan ```command php artisan migrate```, ```composer update/install```, ```npm run dev``` dan ```php artisan serve``` tidak diperlukan untuk membuat origin sinkron dengan upstream. perintah tersebut perlu dilakukan bila kita mau menjalankan aplikasi relawan di lokal.

kasus ini akan dituliskan di wiki terpisah nantinya, apabila sudah dirasa cukup jelas, mohon konfirmasinya supaya issue ini bisa di close, maturnuwun.


ps:
- upstream merujuk pada repo ngesec/relawan
- origin adalah repo hasil fork, dalam kasus ini rexsar/relawan

**Comment by endoch** [comment]
> Btw saya mau menyoroti langkah nomor 5 : composer update, menurut saya jika tidak ada perubahan di composer.json, tidak ada penambahan packages baru, tidak perlu menjalankan composer update, melainkan cukup composer install. Selain itu prosesnya juga lebih cepat dibandingkan composer update.
> 
> composer update biasanya dijalankan jika menambahkan/ada perubahan di file composer.json, atau perlu update packages ke latest version. Dan ini biasanya jarang-jarang. Kalaupun perlu ada update, hanya perlu dilakukan 1 orang, misal oleh lead developer. Karena setiap update version, pasti perlu dicek compability-nya/banyak hal yang perlu dicek.

poin yg baik mas @yohang88, wiki nya akan saya sesuaikan menjadi ```composer install```
maturnuwun

**Comment by resxar** [comment]
maturnuwun @endoch @yohang88 atas tanggapan dan koreksinya.. saya rasa sudah jelas mas, jadi issue ini sudah bisa di close
