### ISSUE TITLE
setting link sosial media + deskripsi singkat posko pada footer menggunakan file .env

### ISSUE THREAD

**Issue by endoch** [NgeSEC/relawan#44]
- link sosial media
  - [ ] twitter
  - [ ] facebook

- deskripsi singkat

tags: view, landing page

**Comment by resxar** [comment]
untuk issue ini sepertinya udah closed oleh:

1. https://github.com/NgeSEC/relawan/pull/58
2. https://github.com/NgeSEC/relawan/pull/60

WTK @Djenova @endoch
