### ISSUE TITLE
Penggunaan nesbot/carbon untuk pengolahan DateTime object yang lebih baik

### ISSUE THREAD

**Issue by yohang88** [NgeSEC/relawan#47]
Dear All.

Saat ini saya lihat app ini belum mengoptimalkan lib untuk pengolahan datetime object di PHP yang lebih mudah dan terutama sesuai "laravel way". 

Ada 1 lib cukup bagus yang sudah disiapkan `class DateFormat` oleh mas @DyanGalih , tapi sepertinya itu `reinventing the wheel`, mengingat laravel sendiri sejak awal sudah menyediakan/menggunakan `nesbot/carbon` https://carbon.nesbot.com

Belum lagi Laravel juga mempunyai fitur Macroable https://murze.be/carbon-is-macroable-in-laravel-55 sehingga format-format datetime, timezone, bisa dihandle lebih baik tanpa harus coding lagi.

Saya mengusulkan untuk merapikan, menyiapkan bagian dari core aplikasi ini terkait pengolahan datetime ini menggunakan `nesbot/carbon`. Termasuk issue-issue localization - format datetime/string dalam bahasa Indonesia. Sehingga ke depan lebih enak untuk digunakan di aplikasi.

Pun saya bersedia membantu mengerjakan ini. 

Ada feedback? 😀

**Comment by DyanGalih** [comment]
Sap. Ganti aja

**Comment by endoch** [comment]
closed pada https://github.com/NgeSEC/relawan/pull/51
