### ISSUE TITLE
Upgrade ke Laravel 5.6 

### ISSUE THREAD

**Issue by yohang88** [NgeSEC/relawan#48]
Dear All.

Saat ini aplikasi masih menggunakan laravel versi 5.5, dan melihat yang terbaru sekarang adalah versi 5.6 (lihat Release Notes https://laravel.com/docs/5.6/releases#laravel-5.6), sepertinya perlu untuk kita upgrade ke versi 5.6, mumpung masih belum banyak codingnya 😀 

Pengalaman update dari 5.5 ke 5.6 cukup mudah. Coba saya bantu jika berkenan.

Ada feedback? 😀

**Comment by Djenova** [comment]
Dear Mas @yohang88 .

Terimakasih banyak atas atensi dan masukannya,
berdasarkan usulan dari mas @DyanGalih dan mengingat proyek ini adalah proyek jangka panjang maka kami memilih laravel 5.5 karena versi tersebut adalah LTS yang akan mendapatkan _Support Bug Fixes_ sampai **30 Agustus 2019** dan _Security Fixes_ sampai **30 Agustus 2020**. 

Apakah ada pertimbangan lain? 😀

![image](https://user-images.githubusercontent.com/7172538/41791336-a797b9ae-767f-11e8-9525-3bcd128a7c9f.png)

Referensi : https://laravel.com/docs/5.6/releases

**Comment by yohang88** [comment]
Terimakasih banyak feedbacknya mas @Djenova .
Memang mungkin ini ada faktor preferensi pribadi juga kali ya haha.

Tapi kurang lebih pendapat saya mirip-mirip artikel ini https://medium.com/@jasonmccreary/laravel-lts-is-a-trap-97b1d1103961 

Dulu pernah nyoba Laravel sejak versi 4, lalu beberapa project nyobain pakai LTS versionyn. Overall sih gak begitu merasakan efek/manfaat dari long term supportnya. Dan makin ketinggalan fitur dari versi-versi terbaru (apalagi Laravel ini cepet banget life/release cycle-nya).

Jadi kalau pendapat saya pribadi, lebih baik:

1. Setiap ada release baru, diusahakan mengikutinya (tapi tetap dipikirkan minor/major changes effortnya). Karena pasti dapat fitur baru + security patches terbaru.

2. Karena kalau LTS, cuma dapat security patches.

Ya itu sih, upgrade ke 5.6 agar mendapatkan fitur2 baru, dapat security patches terbaru, dan tentu saja ekosistem (packages-packages) yang pasti mengikuti versi terbaru juga.

Cmiiw. Butuh feedback kembali 😁

**Comment by Djenova** [comment]
Close, karena berkaitan dengan https://github.com/NgeSEC/relawan/issues/100
