### ISSUE TITLE
Error ketika menjalankan php artisan migrate

### ISSUE THREAD

**Issue by harsxv** [NgeSEC/relawan#59]
Ketika menjalankan `php artisan migrate` muncul error :

>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by harsxv** [comment]
Saya mencoba menambahkan kode di AppServiceProvider.php

`use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}`

Coba menjalankan `php artisan migrate` lagi, dan ternyata sukses.

**Comment by yohang88** [comment]
Ini sering dengar kejadian di Windows dengan settingan XAMPP standard kalau tidak salah.

Workaroundnya memang seperti itu, ditambahkan di `AppServiceProvider`.

Namun di referensi ini: https://laravel-news.com/laravel-5-4-key-too-long-error

> Laravel 5.4 made a change to the default database character set, and it’s now utf8mb4 which includes support for storing emojis. This only affects new applications and as long as you are running MySQL v5.7.7 and higher you do not need to do anything.

Sepertinya bisa di-solve dengan menyesuaikan versi MySQL 5.7 di development, serta menggunakan default charset `utf8mb4` (defaultnya pakai `utf8`).

Mas @harsxv, minta tolong dicoba dulu dengan MySQL 5.7 dan charset `utf8mb4` . Jika memang benar seperti itu, mungkin di `requirement/readme` nanti perlu dilengkapi kembali.

Cmiiw, barangkali ada feedback dari rekan-rekan lain 😀

**Comment by harsxv** [comment]
Terimakasih atas responnya mas @yohang88 .

Oh iya, saya lupa memberitahu info versi yang terinstall di Manjaro Linux saya. Berikut versi di Manjaro Linux:

> mysql  Ver 15.1 Distrib 10.1.33-MariaDB (up to date), for Linux (x86_64) using readline 5.1

**Comment by lantip** [comment]
Kalau menilik release di mariadb, kayaknya ada baiknya diupgrade ke 10.1.34 atau sekalian ke 10.2/10.3 mas.

Kasus ini persis sama dengan ketika mysql saya masih versi 5.3 (kalau gak salah) dan baru solved setelah saya upgrade ke versi 5.7 :D

**Comment by yohang88** [comment]
Menambahkan referensi (lihat selected Answer):
https://stackoverflow.com/questions/45822688/key-was-too-long-in-mariadb-but-same-script-with-same-encoding-works-on-mysql

**Comment by harsxv** [comment]
Setelah saya upgrade ke mariadb 10.1.34 error solved tanpa perlu penambahan kode di AppServiceProvider.php.

Apakah ada masukan lain dari issue ini? Kalau sudah tidak ada, mungkin akan saya closed.

Terimakasih atas masukan dari mas @yohang88 dan mas @lantip

**Comment by lantip** [comment]
@harsxv oke, berarti perlu ditambahkan di readme/requirementnya ya, versi minimal untuk mariadb. 
bisa mas @harsxv sekalian yang edit readme-nya? :D
