### ISSUE TITLE
link dari pop up posko ke halaman detail posko

### ISSUE THREAD

**Issue by endoch** [NgeSEC/relawan#71]
icon posko pada landing page ketika di klik akan muncul pop up berikut:
![link detail info](https://user-images.githubusercontent.com/21161847/42355718-b3654ef8-80f8-11e8-8070-825a7d26d9b4.png)

ketika link "Detail Info>>" di klik, perlu ngelink ke masing-masing halaman detail posko

**Comment by anshori** [comment]
Iya rencananya gitu mas, nunggu datanya oke dulu

**Comment by Djenova** [comment]
Merged! 🎉  https://github.com/NgeSEC/relawan/pull/87
