### ISSUE TITLE
Invalid argument supplied for foreach() - di halaman Posko

### ISSUE THREAD

**Issue by lantip** [NgeSEC/relawan#96]
Ketika masuk ke salah satu kategori/tipe posko, muncul error:

<img width="681" alt="screen shot 2019-03-03 at 01 03 17" src="https://user-images.githubusercontent.com/3334064/53685653-2fcaab00-3d50-11e9-9bc1-032fc36c469d.png">

**Comment by endoch** [comment]
solved pada https://github.com/NgeSEC/relawan/pull/97
